--- #YAML:1.0
name:               Catalyst-Model-Filemaker
version:            0.01
abstract:           Catalyst model for Filemaker's XML services
author:
    - Michele Ongaro <micheleo@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Catalyst::Runtime:    5.80005
    Net::FileMaker::XML::ResultSet:  0
    perl:                 5.008
    Test::More:           0
resources:
    repository:  http://github.com/micheleo/Catalyst--Model--Filemaker
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
